-- AlterEnum
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'REFERRAL_INVITED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'REFERRAL_QUALIFIED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'REFERRAL_REWARDED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'REFERRAL_CAMPAIGN_ACTIVATED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'LOYALTY_POINTS_EARNED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'LOYALTY_TIER_UPGRADED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'REWARD_UNLOCKED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'REWARD_REDEEMED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'SCRATCH_CARD_AVAILABLE';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'SCRATCH_REWARD_REVEALED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'PROMOTION_AVAILABLE';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'COUPON_AVAILABLE';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'COUPON_EXPIRING_SOON';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'INCENTIVE_PROGRESS';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'INCENTIVE_REWARDED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'GOAL_PROGRESS';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'GOAL_COMPLETED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'ACHIEVEMENT_UNLOCKED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'STREAK_MILESTONE';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'SCHEDULED_RIDE_CREATED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'SCHEDULED_RIDE_REMINDER';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'SCHEDULED_RIDE_GENERATED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'SCHEDULED_RIDE_CANCELLED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'SUPPORT_TICKET_CREATED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'SUPPORT_TICKET_UPDATED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'SUPPORT_MESSAGE_RECEIVED';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'INVOICE_READY';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'FAVORITE_DRIVER_AVAILABLE';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'ACCOUNT_SECURITY_UPDATE';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'ADMIN_SOS_ALERT';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'ADMIN_SUPPORT_ESCALATION';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'ADMIN_SETTLEMENT_FAILURE';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'ADMIN_DRIVER_DOCUMENT_PENDING';
ALTER TYPE "notification_type" ADD VALUE IF NOT EXISTS 'ADMIN_CAMPAIGN_LIMIT_REACHED';

-- AlterTable
ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "category" TEXT,
ADD COLUMN IF NOT EXISTS "action_url" TEXT,
ADD COLUMN IF NOT EXISTS "image_asset" TEXT,
ADD COLUMN IF NOT EXISTS "expires_at" TIMESTAMPTZ(6);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "notifications_user_id_category_created_at_idx" ON "notifications"("user_id", "category", "created_at");
